// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgqjnkzrqwqaycyhacia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxncWpua3pycXdxYXljeWhhY2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDE1NjUsImV4cCI6MjA2MTg3NzU2NX0.mqwDp8PsqFvmvdcAihycXtoygyqYKyyXB9YXQ-aTexY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);